extends Node
## Music and sound effects. Sounds are generated by tools/gen_audio.py.

const SFX := ["step", "pickup", "clean", "gift", "quest", "scream", "lift", "thud", "splash", "bleat", "baa",
	"rustle", "giggle", "sleep", "paper", "cook", "ui_move", "ui_select", "ui_open", "ui_close", "error", "blip"]
const MUSIC := ["day", "night", "festival", "title"]

var _sfx := {}
var _music := {}
var _players: Array = []
var _next := 0
var _voice_player: AudioStreamPlayer
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _current_music := ""
var _check := 0.0
var _amb := {}
var _river_amount := 0.0
var _night_amount := 0.0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_ensure_bus("Music")
	_ensure_bus("SFX")
	for n in SFX:
		var path := "res://assets/audio/sfx_%s.wav" % n
		if ResourceLoader.exists(path):
			_sfx[n] = load(path)
	for m in MUSIC:
		var path := "res://assets/audio/music_%s.ogg" % m
		if ResourceLoader.exists(path):
			var s: AudioStream = load(path)
			if s is AudioStreamOggVorbis:
				(s as AudioStreamOggVorbis).loop = true
			_music[m] = s
	for i in range(10):
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_players.append(p)
	_voice_player = AudioStreamPlayer.new()
	_voice_player.bus = "SFX"
	add_child(_voice_player)
	_music_a = AudioStreamPlayer.new()
	_music_a.bus = "Music"
	add_child(_music_a)
	_music_b = AudioStreamPlayer.new()
	_music_b.bus = "Music"
	add_child(_music_b)
	for a in ["day", "night", "river"]:
		var path := "res://assets/audio/amb_%s.ogg" % a
		if ResourceLoader.exists(path):
			var st: AudioStream = load(path)
			if st is AudioStreamOggVorbis:
				(st as AudioStreamOggVorbis).loop = true
			var ap := AudioStreamPlayer.new()
			ap.bus = "SFX"
			ap.stream = st
			ap.volume_db = -60.0
			add_child(ap)
			ap.play()
			_amb[a] = ap
	apply_volumes()


func _ensure_bus(bus_name: String) -> void:
	if AudioServer.get_bus_index(bus_name) == -1:
		AudioServer.add_bus()
		var idx := AudioServer.bus_count - 1
		AudioServer.set_bus_name(idx, bus_name)
		AudioServer.set_bus_send(idx, "Master")


static func _lin_db(v: float) -> float:
	if v <= 0.001:
		return -80.0
	return linear_to_db(v)


func apply_volumes() -> void:
	var m := AudioServer.get_bus_index("Music")
	var s := AudioServer.get_bus_index("SFX")
	if m >= 0:
		AudioServer.set_bus_volume_db(m, _lin_db(float(Game.settings.get("music", 0.7))) - 4.0)
	if s >= 0:
		AudioServer.set_bus_volume_db(s, _lin_db(float(Game.settings.get("sfx", 0.8))))


func sfx(sfx_name: String, pitch := 1.0, volume_db := 0.0) -> void:
	if not _sfx.has(sfx_name):
		return
	var p: AudioStreamPlayer = _players[_next]
	_next = (_next + 1) % _players.size()
	p.stream = _sfx[sfx_name]
	p.pitch_scale = clampf(pitch, 0.3, 3.0)
	p.volume_db = volume_db
	p.play()


## Animal Crossing style speech blip.
func voice(pitch: float) -> void:
	if not _sfx.has("blip"):
		return
	_voice_player.stream = _sfx["blip"]
	_voice_player.pitch_scale = clampf(pitch * randf_range(0.88, 1.14), 0.3, 3.0)
	_voice_player.volume_db = -9.0
	_voice_player.play()


func play_music(music_name: String) -> void:
	if music_name == "title" and not _music.has("title"):
		music_name = "day"
	if music_name == _current_music or not _music.has(music_name):
		return
	_current_music = music_name
	var old := _music_a if _music_a.playing else _music_b
	var new := _music_b if old == _music_a else _music_a
	new.stream = _music[music_name]
	new.volume_db = -30.0
	new.play()
	var tw := create_tween()
	tw.set_parallel(true)
	tw.tween_property(new, "volume_db", 0.0, 2.5)
	if old.playing:
		tw.tween_property(old, "volume_db", -40.0, 2.5)
		tw.chain().tween_callback(old.stop)


func update_music() -> void:
	if not Game.playing:
		return
	var h := Game.minutes / 60.0
	if Game.has_flag("festival_ready") and not Game.has_flag("festival_done") and h >= 19.5:
		play_music("festival")
	elif h >= 20.5 or h < 6.0:
		play_music("night")
	else:
		play_music("day")


## 0..1 how close the listener is to running water.
func set_river_amount(v: float) -> void:
	_river_amount = clampf(v, 0.0, 1.0)


func set_night_amount(v: float) -> void:
	_night_amount = clampf(v, 0.0, 1.0)


func _amb_level(key: String, v: float, base_db: float, delta: float) -> void:
	if not _amb.has(key):
		return
	var p: AudioStreamPlayer = _amb[key]
	var target := base_db + linear_to_db(maxf(v, 0.0005))
	p.volume_db = lerpf(p.volume_db, target, clampf(delta * 1.5, 0.0, 1.0))


func _process(delta: float) -> void:
	_amb_level("day", 1.0 - _night_amount, -19.0, delta)
	_amb_level("night", _night_amount, -17.0, delta)
	_amb_level("river", _river_amount, -13.0, delta)
	_check -= delta
	if _check <= 0.0:
		_check = 4.0
		if Game.playing and _current_music != "festival":
			update_music()
